version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "3000:80"

  server-john:
    build: ./server
    expose:
    - "3000"
    environment:
      - NAME=John

  # server-paul:
  #   build: ./server
  #   expose:
  #     - "3000"
  #   environment:
  #     - NAME=Paul

  # server-george:
  #   build: ./server
  #   expose:
  #     - "3000"
  #   environment:
  #     - NAME=George

  # server-ringo:
  #   build: ./server
  #   expose:
  #     - "3000"
  #   environment:
  #     - NAME=Ringo

  # client:
  #   build: ./client

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
volumes:
  redisdata:
